In [1]:
!pip3 install numpy


[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: pip install --upgrade pip


In [2]:
import numpy as np

In [3]:
print(np.__version__)

1.26.4


In [4]:
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
#Using Tupple to create an ndarray

arrTuples = np.array((1,2,3,4,5))
print(arrTuples)
print(type(arrTuples))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [6]:
zeroDim = np.array(10)
oneDim = np.array([1,2,3,4,5])
twoDim = np.array([[1,2,3],[4,5,6]])
threeDim = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print(zeroDim)
print(oneDim)
print(twoDim)   
print(threeDim)

10
[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [4]:
!pip3 install kagglehub


[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: pip install --upgrade pip


In [5]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("valakhorasani/mobile-device-usage-and-user-behavior-dataset")

print("Path to dataset files:", path)

/Users/macbook/Desktop/NLP/myenv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


100%|██████████| 11.3k/11.3k [00:00<00:00, 4.36MB/s]

Extracting files...
Path to dataset files: /Users/macbook/.cache/kagglehub/datasets/valakhorasani/mobile-device-usage-and-user-behavior-dataset/versions/1
