In [1]:
!pip3 install numpy


[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: pip install --upgrade pip


In [2]:
import numpy as np

In [3]:
print(np.__version__)

1.26.4


In [4]:
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
#Using Tupple to create an ndarray

arrTuples = np.array((1,2,3,4,5))
print(arrTuples)
print(type(arrTuples))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [6]:
zeroDim = np.array(10)
oneDim = np.array([1,2,3,4,5])
twoDim = np.array([[1,2,3],[4,5,6]])
threeDim = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print(zeroDim)
print(oneDim)
print(twoDim)   
print(threeDim)

10
[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
